apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged_policy
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
rule: 'RunAsAny'
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-team
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: dev-team-service-account
 namespace: dev-team
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: dev-team
  name: dev-team-deploy-role
  rules:
  - apiGroups: [“extensions”, “apps”]
    resources: [“deployments”]
    verbs: [“get”, “create”, “update”, “patch”]
  - apiGroups: [“”]
    resources: [“services”]
    verbs: [“get”, “create”, “update”, “patch”]
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
    - privileged_policy
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
 name: dev-team-binding
 namespace: dev-team
subjects:
- kind: ServiceAccount
  name: dev-team-service-account
  namespace: dev-team
 roleRef:
  kind: Role
  name: dev-team-deploy-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-team-binding
  namespace: dev-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-team-deploy-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user-1
